### Test add
POST http://localhost:8080/add
Content-Type: application/json
X-API-Key: demo

{
  "key": "test_key2",
  "topic": "test_topic",
  "content": "This is a large article that talks about apples and oranges in Go.",
  "extra": "some extra information"
}
### Test get
GET http://localhost:8080/get?key=test_key2&topic=test_topic
X-API-Key: demo

### Test fuzzy search
GET http://localhost:8080/search?q=APPLESSE&topic=test_topic
X-API-Key: demo