name: Build Go Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # or your preferred version

      - name: Build
        run: go build -o goStore main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: goStore
          path: goStore

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: goStore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}